/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import javax.swing.JPanel;

/**
 *
 * @author SHAD40
 */
public class PanelCamino extends JPanel {
    /**
     * Creates new form PanelCamino
     */
    public PanelCamino() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChckCaminoEuler = new javax.swing.JCheckBox();
        ChckCaminoHamilton = new javax.swing.JCheckBox();
        ChckCicloEuler = new javax.swing.JCheckBox();
        ChckCicloHamilton = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCiEuler = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCaEuler = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtCaHamilton = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtCiHamilton = new javax.swing.JTextArea();

        setEnabled(false);

        ChckCaminoEuler.setText("Camino de Euler");
        ChckCaminoEuler.setEnabled(false);

        ChckCaminoHamilton.setText("Camino de Hamilton");
        ChckCaminoHamilton.setEnabled(false);

        ChckCicloEuler.setText("Ciclo de Euler");
        ChckCicloEuler.setEnabled(false);

        ChckCicloHamilton.setText("Ciclo de Hamilton");
        ChckCicloHamilton.setEnabled(false);

        txtCiEuler.setEditable(false);
        txtCiEuler.setColumns(20);
        txtCiEuler.setRows(5);
        jScrollPane1.setViewportView(txtCiEuler);

        txtCaEuler.setEditable(false);
        txtCaEuler.setColumns(20);
        txtCaEuler.setRows(5);
        jScrollPane2.setViewportView(txtCaEuler);

        txtCaHamilton.setEditable(false);
        txtCaHamilton.setColumns(20);
        txtCaHamilton.setRows(5);
        jScrollPane3.setViewportView(txtCaHamilton);

        txtCiHamilton.setEditable(false);
        txtCiHamilton.setColumns(20);
        txtCiHamilton.setRows(5);
        jScrollPane4.setViewportView(txtCiHamilton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChckCaminoEuler)
                    .addComponent(ChckCaminoHamilton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChckCicloEuler)
                    .addComponent(ChckCicloHamilton))
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(225, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChckCaminoEuler)
                    .addComponent(ChckCicloEuler))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChckCicloHamilton)
                    .addComponent(ChckCaminoHamilton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(195, Short.MAX_VALUE)))
        );

        ChckCaminoEuler.getAccessibleContext().setAccessibleName("ChkCaminoEuler");
        ChckCaminoHamilton.getAccessibleContext().setAccessibleName("ChckCaminoHamilton");
        ChckCicloEuler.getAccessibleContext().setAccessibleName("ChckCicloEuler");
        ChckCicloHamilton.getAccessibleContext().setAccessibleName("ChckCicloHamilton");

        getAccessibleContext().setAccessibleName("paneChck");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ChckCaminoEuler;
    private javax.swing.JCheckBox ChckCaminoHamilton;
    private javax.swing.JCheckBox ChckCicloEuler;
    private javax.swing.JCheckBox ChckCicloHamilton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea txtCaEuler;
    private javax.swing.JTextArea txtCaHamilton;
    private javax.swing.JTextArea txtCiEuler;
    private javax.swing.JTextArea txtCiHamilton;
    // End of variables declaration//GEN-END:variables
}
