
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.border.Border;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LENOVO
 */
public class UI extends javax.swing.JPanel {
    
    private JPanel panelCaminos,panelBotones;
    private JButton btnGenerar,btnEliminar;
    private JCheckBox checkCaminoEuler,checkCicloEuler,checkCaminoHaminton,checkCicloHaminton;
    private JTextArea txtCaminoEuler,txtCicloEuler,txtCaminoHaminton,txtCicloHaminton;
    private JLabel lb;

    /**
     * Creates new form UI
     */
    public UI() {
        iniciarComponentes();
    }
    
    
    private void iniciarComponentes(){
        this.setLayout(new BorderLayout());
        panelBotones();
        Lienzo lienzo= new Lienzo();
        panelBotones();
        this.add(panelBotones,BorderLayout.SOUTH);
        this.add(lienzo, BorderLayout.CENTER);        
        panelCaminos();
        this.add(panelCaminos,BorderLayout.EAST);
        
    }
    
    private void panelBotones(){
        panelBotones = new JPanel(new GridLayout(1,2));
        panelBotones.setBounds(0,0, 500, 20);
        panelBotones.add(btnGenerar = new JButton("Generar"));
        panelBotones.add(btnEliminar = new JButton("Limpiar"));
    }
    
    private void panelCaminos(){
        //Panel para caminos
        panelCaminos = new JPanel(new GridLayout(4,3));
        Border border = BorderFactory.createLineBorder(Color.BLACK);      
        //camino de euler check
        checkCaminoEuler = new JCheckBox("Camino de Euler");
        checkCaminoEuler.setEnabled(false);
        panelCaminos.add(checkCaminoEuler);
        //ciclo de euler check
        checkCicloEuler = new JCheckBox("Ciclo de Euler");
        checkCicloEuler.setEnabled(false);
        panelCaminos.add(checkCicloEuler);
        //camino de euler text area
        txtCaminoEuler = new JTextArea();
        txtCaminoEuler.setBorder(BorderFactory.createCompoundBorder(border, 
            BorderFactory.createEmptyBorder(10, 10, 10, 10)));
        panelCaminos.add(txtCaminoEuler);
        //ciclo de euler text area
        txtCicloEuler = new JTextArea();
        txtCicloEuler.setBorder(BorderFactory.createCompoundBorder(border,
                BorderFactory.createEmptyBorder(10,10,10,10)));        
        panelCaminos.add(txtCicloEuler);        
        //camino haminton check
        checkCaminoHaminton =  new JCheckBox("Camino de Haminton");
        checkCaminoHaminton.setEnabled(false);
        panelCaminos.add(checkCaminoHaminton);
        //ciclo haminton check
        checkCicloHaminton = new JCheckBox("Ciclo de Haminton");
        checkCicloHaminton.setEnabled(false);
        panelCaminos.add(checkCicloHaminton);
        //Text area camino haminton
        txtCaminoHaminton = new JTextArea();
        txtCaminoHaminton.setBorder(BorderFactory.createCompoundBorder(border,
                BorderFactory.createEmptyBorder(10,10,10,10)));  
        panelCaminos.add(txtCaminoHaminton);
        //Text area ciclo haminton
        txtCicloHaminton = new JTextArea();
        txtCicloHaminton.setBorder(BorderFactory.createCompoundBorder(border,
                BorderFactory.createEmptyBorder(10,10,10,10)));  
        panelCaminos.add(txtCicloHaminton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
